# Please refer https://aka.ms/HTTPSinContainer on how to setup an https developer certificate for your ASP.NET Core service.

version: '3.4'

services:
  planitapi:
    image: planitapi
    container_name: planit_api
    depends_on:
      - planitdb
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - 8080:80
    environment:
      - TestEnvVar="test-value"
      - ConnectionStrings__PlanItDBConnectionString=server=planitdb;port=3306;database=dev_db;user=root;password=Abc12345

  planitdb:
    image: mysql
    container_name: planit_db
    environment:
      MYSQL_ROOT_PASSWORD: Abc12345
      MYSQL_DATABASE: dev_db
    ports:
      - "3307:3306"
