# Please refer https://aka.ms/HTTPSinContainer on how to setup an https developer certificate for your ASP.NET Core service.

version: '3.4'

services:
  planitapi:
    image: planitapi
    container_name: planit_api
    depends_on:
      - planitdb
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - 8080:80
    environment:
      - ConnectionStrings__PlanItDBConnectionString=Host=planitdb;Database=dev_db;Username=postgres;Password=Abc12345

  planitdb:
    image: postgres
    container_name: planit_db
    environment:
      POSTGRES_PASSWORD: Abc12345
      POSTGRES_DB: dev_db
    ports:
      - "5432:5432"
