// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using PlanIt.API.DbContexts;

#nullable disable

namespace PlanIt.API.Migrations
{
    [DbContext(typeof(PlanItDbContext))]
    partial class PlanItDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.13")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("PlanIt.API.Entities.Experience", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("City")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<string>("Country")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<string>("Description")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<string>("State")
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<int>("UserId")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("Experiences");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            City = "Amsterdam",
                            Country = "Netherlands",
                            Description = "Experience the beauty of Amsterdam’s canals by going on this scenic cruise. Pass by Anne Frank House, the Jordaan, the Houseboat Museum, Leiden Square, Rijksmuseum, De Duif and much more.",
                            Title = "Amsterdam Open Boat Canal Cruise - Live Guide - from Anne Frank House",
                            UserId = 1
                        },
                        new
                        {
                            Id = 2,
                            City = "Dubai",
                            Country = "United Arab Emirates",
                            Description = "Experience several desert pursuits in one outing, including ATV-driving—something many tours only offer at an extra cost—on this red-dune desert tour from Dubai. Skip the hassle of transport and logistical planning; and be free to simply enjoy the dunes and activities provided. Zoom off on an ATV, ride a camel, go sandboarding; enjoy henna art and Arabian-costume photos; and conclude with a barbecue-buffet dinner and live shows.",
                            Title = "Dubai: Red Dunes Quad Bike, Sandsurf, Camels & BBQ at Al Khayma Camp",
                            UserId = 1
                        },
                        new
                        {
                            Id = 3,
                            City = "Haleiwa",
                            Country = "United States",
                            Description = "Skip the hassle of renting a car and see the highlights of Oahu’s North Shore from the comfort of a minibus or van. Along the way, a guide keeps you entertained and shares details about the island that you would likely miss if traveling on your own. At each stop, you can enjoy free time to swim, shop, paddleboard/kayak or do an optional waterfall hike while getting to know the island.",
                            State = "Hawaii",
                            Title = "Tour of North Shore and Sightseeing",
                            UserId = 2
                        },
                        new
                        {
                            Id = 4,
                            City = "London",
                            Country = "United Kingdom",
                            Description = "This historic castle with over 1,000 years of history is home to the Crown Jewels, the iconic 'Beefeater' Yeoman Warders, and the legendary ravens that have kept the kingdom from collapsing. Inside the White Tower, the oldest building of the castle, is an 11th-century chapel and historic Royal Armouries collections.",
                            Title = "Tower of London",
                            UserId = 2
                        },
                        new
                        {
                            Id = 5,
                            City = "Seoul",
                            Country = "South Korea",
                            Description = "The National Museum of Korea and the National Folk Museum are located on the grounds of this palace, built six centuries ago by the founder of the Chosun dynasty.",
                            Title = "Gyeongbokgung Palace",
                            UserId = 3
                        },
                        new
                        {
                            Id = 6,
                            City = "Marrakech",
                            Country = "Morocco",
                            Description = "Nicely designed and maintained gardens, similar to those of Generalife in Granada, Spain. It’s a good place to recoup from the intensity of the market atmosphere.",
                            Title = "Jardin Majorelle",
                            UserId = 3
                        });
                });

            modelBuilder.Entity("PlanIt.API.Entities.Rating", b =>
                {
                    b.Property<int>("UserId")
                        .HasColumnType("integer");

                    b.Property<int>("ExperienceId")
                        .HasColumnType("integer");

                    b.Property<int>("StarCount")
                        .HasColumnType("integer");

                    b.HasKey("UserId", "ExperienceId");

                    b.HasIndex("ExperienceId");

                    b.ToTable("Ratings");

                    b.HasData(
                        new
                        {
                            UserId = 1,
                            ExperienceId = 1,
                            StarCount = 5
                        },
                        new
                        {
                            UserId = 1,
                            ExperienceId = 2,
                            StarCount = 4
                        },
                        new
                        {
                            UserId = 2,
                            ExperienceId = 1,
                            StarCount = 2
                        });
                });

            modelBuilder.Entity("PlanIt.API.Entities.User", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<string>("Username")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.HasKey("Id");

                    b.ToTable("Users");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Email = "joe@blow.com",
                            Username = "joeblow"
                        },
                        new
                        {
                            Id = 2,
                            Email = "mickey@disney.com",
                            Username = "mickey.mouse"
                        },
                        new
                        {
                            Id = 3,
                            Email = "user@gmail.com",
                            Username = "anonymous"
                        });
                });

            modelBuilder.Entity("PlanIt.API.Entities.Experience", b =>
                {
                    b.HasOne("PlanIt.API.Entities.User", "User")
                        .WithMany("Experiences")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("PlanIt.API.Entities.Rating", b =>
                {
                    b.HasOne("PlanIt.API.Entities.Experience", "Experience")
                        .WithMany("Ratings")
                        .HasForeignKey("ExperienceId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("PlanIt.API.Entities.User", "User")
                        .WithMany("Ratings")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Experience");

                    b.Navigation("User");
                });

            modelBuilder.Entity("PlanIt.API.Entities.Experience", b =>
                {
                    b.Navigation("Ratings");
                });

            modelBuilder.Entity("PlanIt.API.Entities.User", b =>
                {
                    b.Navigation("Experiences");

                    b.Navigation("Ratings");
                });
#pragma warning restore 612, 618
        }
    }
}
